### ISSUE TITLE
NO save of High Score

### ISSUE THREAD

**Issue by bigfoot53** [MiSTer-devel/Arcade-Berzerk_MiSTer#3]
Hello Is it possible to retain the high scores ?

Thanks
Bruce

**Comment by sorgelig** [comment]
None of arcades save the highscores.

**Comment by bigfoot53** [comment]
Is this a Hardware issue or sometnign else ? 
WIll the save feature eventually work ?

Thanks

**Comment by sorgelig** [comment]
It's not implemented, it's not automatic. So someone need to write such code for every arcade, and each arcade has different way to work with non-volatile memory.
I have no plans to support it as it's completely useless from my point of view.

You or anyone else can add support if they care.

**Comment by bigfoot53** [comment]
Thanks for the info :) 
I'm Not a code but might have to give it a try :)  Berzerk is MY favorite. Restoring a cabinet and replacing the boards with a mister fpga so it would be great to have the save feature :) 

Thanks
Bruce

**Comment by JimmyStones** [comment]
Hi @sorgelig - I think this issue can be closed since we added NVRAM support last month :)
